language: csharp
script:
  - xbuild /p:Configuration=Travis EE.FutureProof/EE.FutureProof.csproj
install:
  - nuget restore EE.FutureProof/packages.config -SolutionDirectory . -Verbosity detailed
branches:
  only: 
    - master